export default [
    {
        id: 1,
        slug: 'house_3rooms',
        main_img: '/base_image/main_img/3rooms_house.jpg',
        title: 'Дім трикімнатний.',
        description: 'дім трикімнатний 4000грн/доба',
        images: [
            '/base_image/house_3rooms_img/photo_1.jpg',
            '/base_image/house_3rooms_img/photo_2.jpg',
            '/base_image/house_3rooms_img/photo_3.jpg',
            '/base_image/house_3rooms_img/photo_4.jpg',
            '/base_image/house_3rooms_img/photo_5.jpg',
            '/base_image/house_3rooms_img/photo_6.jpg',
            '/base_image/house_3rooms_img/photo_7.jpg',
            '/base_image/house_3rooms_img/photo_8.jpg',
            '/base_image/house_3rooms_img/photo_9.jpg',
            '/base_image/house_3rooms_img/photo_10.jpg',
            '/base_image/house_3rooms_img/photo_11.jpg',
            '/base_image/house_3rooms_img/photo_12.jpg',
            '/base_image/house_3rooms_img/photo_13.jpg',
            '/base_image/house_3rooms_img/photo_14.jpg',
            '/base_image/house_3rooms_img/photo_15.jpg',
            '/base_image/house_3rooms_img/photo_16.jpg',
            '/base_image/house_3rooms_img/photo_17.jpg',
            '/base_image/house_3rooms_img/photo_18.jpg',
            '/base_image/house_3rooms_img/photo_19.jpg',
            '/base_image/house_3rooms_img/photo_20.jpg',
            '/base_image/house_3rooms_img/photo_21.jpg',
        ]
    },
    {
        id: 2,
        slug: 'room_with_bedroom',
        main_img: '/base_image/main_img/room_3person_2500.jpg',
        title: 'Номер на трьох осіб- номер кухня плюс спальня',
        description: 'номер кухня + спальня 2500грн/доба',
        images: [
            '/base_image/room_with_bedroom_img/photo_1.jpg',
            '/base_image/room_with_bedroom_img/photo_2.jpg',
            '/base_image/room_with_bedroom_img/photo_3.jpg',
            '/base_image/room_with_bedroom_img/photo_4.jpg',
            '/base_image/room_with_bedroom_img/photo_5.jpg',
            '/base_image/room_with_bedroom_img/photo_6.jpg',
            '/base_image/room_with_bedroom_img/photo_7.jpg',
            '/base_image/room_with_bedroom_img/photo_8.jpg',
            '/base_image/room_with_bedroom_img/photo_9.jpg',
            '/base_image/room_with_bedroom_img/photo_10.jpg',
        ]
    },
    {
        id: 3,
        slug: 'room_with_double_bed_and_sofa',
        main_img: '/base_image/main_img/studio_2000grn.jpg',
        title: 'Номер студія двоспальне ліжко і розкладний диван 2000 грн доба.',
        description: 'Номер-студія-2000 грн',
        images: [
            '/base_image/room_with_double_bed_and_sofa_img/photo_1.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_2.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_3.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_4.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_5.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_6.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_7.jpg',
            '/base_image/room_with_double_bed_and_sofa_img/photo_8.jpg',
        ]
    },
    {
        id: 4,
        slug: 'room_studio_2person',
        main_img: '/base_image/main_img/studio_1500grn.jpg',
        title: 'Номер студія 1500 грн',
        description: 'Номер студія 1500 грн',
        images: [
            '/base_image/room_studio_2person_img/photo_1.jpg',
            '/base_image/room_studio_2person_img/photo_2.jpg',
            '/base_image/room_studio_2person_img/photo_3.jpg',
            '/base_image/room_studio_2person_img/photo_4.jpg',
            '/base_image/room_studio_2person_img/photo_5.jpg',
            '/base_image/room_studio_2person_img/photo_6.jpg',
            '/base_image/room_studio_2person_img/photo_7.jpg',
            '/base_image/room_studio_2person_img/photo_8.jpg',
            '/base_image/room_studio_2person_img/photo_9.jpg',
            '/base_image/room_studio_2person_img/photo_10.jpg',
        ]
    },
    {
        id: 5,
        slug: 'room_studio_4person',
        main_img: '/base_image/main_img/studio_4person.jpg',
        title: 'Номер- студія на чотирьох осіб 2000грн.',
        description: 'Номер- студія на чотирьох осіб 2000 грн',
        images: [
            '/base_image/room_studio_4person_img/photo_1.jpg',
            '/base_image/room_studio_4person_img/photo_2.jpg',
            '/base_image/room_studio_4person_img/photo_3.jpg',
            '/base_image/room_studio_4person_img/photo_4.jpg',
            '/base_image/room_studio_4person_img/photo_5.jpg',
            '/base_image/room_studio_4person_img/photo_6.jpg',
            '/base_image/room_studio_4person_img/photo_7.jpg',
            '/base_image/room_studio_4person_img/photo_8.jpg',
            '/base_image/room_studio_4person_img/photo_9.jpg',
            '/base_image/room_studio_4person_img/photo_10.jpg',
            '/base_image/room_studio_4person_img/photo_11.jpg',
            '/base_image/room_studio_4person_img/photo_12.jpg',
        ]
    },
    {
            id: 6,
            slug: 'kitchen',
            main_img: '/base_image/main_img/kitchen.jpg',
            title: 'Комплектація кухні',
            description: 'Комплектація кухні',
            images: [
                '/base_image/kitchen_img/photo_1.jpg',
                '/base_image/kitchen_img/photo_2.jpg',
                '/base_image/kitchen_img/photo_3.jpg',
                '/base_image/kitchen_img/photo_4.jpg',
                '/base_image/kitchen_img/photo_5.jpg',
                '/base_image/kitchen_img/photo_6.jpg',
                '/base_image/kitchen_img/photo_7.jpg',
                '/base_image/kitchen_img/photo_8.jpg',
                '/base_image/kitchen_img/photo_9.jpg',
            ]
        },

];



